---
- name: Check compiled files
  stat:
    path: /usr/local/lib/libmpd.so.1.3.0
  register: libmpd_so

- name: Install Development Tools
  become: true
  package:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - "glib2-devel"
  when: libmpd_so.stat.exists == False

- name: Extract source code
  become: true
  unarchive:
    src: "http://download.sarine.nl/Programs/gmpc/11.8/{{ libmpd_var }}.tar.gz"
    dest: "{{ src_dir }}"
    remote_src: yes
    owner: ansible
    group: wheel
  when: libmpd_so.stat.exists == False

- name: Execute ./configure
  command: chdir="{{ src_dir }}/{{ libmpd_var }}" ./configure
  when: libmpd_so.stat.exists == False

- name: Execute make
  command: chdir="{{ src_dir }}/{{ libmpd_var }}" make
  when: libmpd_so.stat.exists == False

- name: Execute make install
  become: true
  command: chdir="{{ src_dir }}/{{ libmpd_var }}" make install
  when: libmpd_so.stat.exists == False

- name: Execute make clean
  command: chdir="{{ src_dir }}/{{ libmpd_var }}" make clean
  when: libmpd_so.stat.exists == False
