---
- name: Install Development Tools
  become: true
  package:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - "@development"

- name: Install libmpd
  include: install-libmpd.yml

- name: Install GMPC
  include: install-gmpc.yml
